use std::collections::HashMap;

pub fn get_kwords() -> HashMap<&'static str, Token> {
    HashMap::from([
        ("dflow", Token::Dflow),
        ("module", Token::Module),
        ("library", Token::Library),
        ("component", Token::Component),
        ("return", Token::Return),
        ("fn", Token::Fn),
        ("let", Token::Let),
        ("while", Token::While),
        ("for", Token::For),
        ("in", Token::In),
        ("range", Token::Range),
        ("if", Token::If),
        ("else", Token::Else),
        ("struct", Token::Struct),
        ("_init", Token::Init),
        ("_call", Token::Call),
        ("impl", Token::Impl),
        ("as", Token::As),
        ("priv", Token::Priv),
        ("pre", Token::Pre),
        ("post", Token::Post),
        ("break", Token::Break),
        ("continue", Token::Continue),
        ("exec", Token::Exec),
        ("bind", Token::Bind),
        ("mut", Token::Mut),
        ("or", Token::Or),
        ("and", Token::And),
        ("not", Token::Not),
        ("u32", Token::U32),
        ("i32", Token::I32),
        ("f32", Token::F32),
        ("u64", Token::U64),
        ("i64", Token::I64),
        ("f64", Token::F64),
        ("u8", Token::U8),
        ("vec", Token::Vec),
        ("bool", Token::Bool),
        ("str", Token::String),
        ("false", Token::False),
        ("true", Token::True),
        ("m", Token::M),
    ])
}

pub fn get_ll1_operators() -> HashMap<&'static str, Token> {
    HashMap::from([
        ("{", Token::LBrace),
        ("}", Token::RBrace),
        ("(", Token::LParen),
        (")", Token::RParen),
        ("[", Token::LBracket),
        ("]", Token::RBracket),
        ("+", Token::Plus),
        ("*", Token::Star),
        ("/", Token::Div),
        (":", Token::Colon),
        (";", Token::Semi),
        (",", Token::Coma),
        (".", Token::Dot),
        ("!=", Token::NotEqual),
    ])
}

pub fn get_ll2_operators() -> HashMap<&'static str, Token> {
    HashMap::from([
        ("-", Token::Minus),
        ("->", Token::RArrow),
        ("=", Token::Assign),
        ("==", Token::Equal),
        ("<", Token::Less),
        ("<=", Token::LessEqual),
        (">", Token::Greater),
        (">=", Token::GreaterEqual),
    ])
}

#[derive(Clone, PartialEq, Debug)]
pub enum Token {
    Dflow,
    Module,
    Library,
    Component,
    Return,
    Fn,
    Let,
    While,
    For,
    In,
    Range,
    If,
    Else,
    Struct,
    Init,
    Call,
    Impl,
    As,
    Priv,
    Pre,
    Post,
    Break,
    Continue,
    Exec,
    Bind,
    Mut,
    Or,
    And,
    Not,
    U32,
    I32,
    F32,
    U64,
    I64,
    F64,
    U8,
    Vec,
    Bool,
    String,
    LBrace,
    RBrace,
    LParen,
    RParen,
    LBracket,
    RBracket,
    Plus,
    Minus,
    Star,
    Div,
    Colon,
    Semi,
    Coma,
    Dot,
    Assign,
    Less,
    Greater,
    LessEqual,
    GreaterEqual,
    Equal,
    NotEqual,
    RArrow,
    True,
    False,
    M,
    StringLiteral(String),
    IntegerLiteral(String),
    FloatingLiteral(String),
    Identifier(String),
    EndOfText,
}
