typeSpecifier = 
  dflowSpecifier
  | componentSpecifier
  | implSpecifier
  | structSpecifier
;

moduleDeclaration = 
  Module
  LeftBrace
  typeSpecifiers
  RightBrace
  Semi
;

typeSpecifiers = typeSpecifier, {typeSpecifier};

libraryDeclaration = 
  Library
  LeftBrace
  functionDefinitions
  RightBrace
  Semi
;

functionDefinitions = functionDefinition, {functionDefinition};

dflowSpecifier = 
  Dflow 
  dflowId
  LeftBrace
  stages 
  RightBrace 
  Semi
;

componentSpecifier = 
  Compnt
  componentId
  LeftBrace
  initMethod
  callMethod
  members
  RightBrace
  Semi 
;

implSpecifier = 
  Impl
  dflowId
  As
  implDflowId
  LeftBrace
  StageAssignments
  RightBrace
  Semi
;

functionDefinition = 
  Fn
  Identifier
  LeftParen
  Args
  RightParen
  ReturnType
  Contract
  LeftBrace
  Statements
  RightBrace
  Semi
;

structSpecifier = 
  Struct
  TypeName
  LeftBrace
  TypeName
  Fields
  RightBrace
  Semi
;
